defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
summaryLength = 30

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[outputFormats.MasonryData]
  mediaType = "application/json"
  baseName = "data"
  isPlainText = true
  notAlternative = true

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5
