# Intentional overrides for the Redefine demo site.
# All other values inherit from the theme's root _config.yml.

defaults:
  logo: /images/redefine-favicon.svg

fontawesome:
  thin: true
  light: true
  duotone: true
  sharp_solid: true

home_banner:
  subtitle:
    text:
      - Redefine your writing.
      - A simple, fast and pure theme.
    smart_backspace: false
  social_links:
    enable: true
    links:
      - icon: github
        url: https://github.com/EvanNotFound/hexo-theme-redefine
      - icon: npm
        url: https://www.npmjs.com/package/hexo-theme-redefine
      - icon: email
        url: mailto:contact@ohevan.com

navbar:
  links:
    Archives:
      path: /archives
      icon: fa-regular fa-archive
    Docs:
      path: https://redefine-docs.ohevan.com
      icon: fa-regular fa-book
    Github:
      path: https://github.com/EvanNotFound/hexo-theme-redefine
      icon: fa-brands fa-github
    Links:
      icon: fa-regular fa-link
      submenus:
        About: https://ohevan.com/about
        Blog: https://ohevan.com
        Showcase: /showcase

home:
  sidebar:
    announcement: Redefine your writing.
    links:
      Archives:
        path: /archives
        icon: fa-regular fa-archive
      Tags:
        path: /tags
        icon: fa-regular fa-tags
      Categories:
        path: /categories
        icon: fa-regular fa-folder
      Shuoshuo:
        path: /essays
        icon: fa-regular fa-comment-dots
      Photos:
        path: /masonry
        icon: fa-regular fa-images
      Bookmarks:
        path: /bookmarks
        icon: fa-regular fa-bookmark

articles:
  author_label:
    list:
      - MVP++
  pangu_js: true
  recommendation:
    enable: true

comment:
  config:
    waline:
      serverUrl: https://redefine-waline.ohevan.com

footer:
  icon: '<i class="fa-solid fa-code-pull-request"></i>'

inject:
  enable: true
  footer:
    - <script defer src="https://events.ohevan.com/script.js" data-website-id="d70a02b2-4de2-4995-8a26-7bc745a8b460"></script>

plugins:
  feed:
    enable: true
  aplayer:
    type: mini
    audios:
      - name: Something Just Like This
        artist: Coldplay
        url: https://files.catbox.moe/dzyo1p.mp3
        cover: https://files.catbox.moe/phd1di.png
      - name: Fly Away
        artist: Tones and I
        url: https://files.catbox.moe/qusdqv.mp3
        cover: https://files.catbox.moe/5j1gtl.png
      - name: September
        artist: Earth, Wind & Fire
        url: https://files.catbox.moe/v6m4fj.mp3
        cover: https://files.catbox.moe/rzwise.jpg
      - name: Imagine
        artist: John Lennon
        url: https://files.catbox.moe/9nl42v.mp3
        cover: https://files.catbox.moe/h85s6u.jpg
      - name: 7 Years
        artist: Lukas Graham
        url: https://files.catbox.moe/te9l6r.mp3
        cover: https://files.catbox.moe/bg4gro.jpg
  mermaid:
    enable: true
