# Hexo settings specific to the Redefine demo site.
# Unlisted values use Hexo's defaults.

title: Theme Redefine
subtitle: Redefine Theme Demo Site
description: This is Hexo Theme Redefine official demo site. You can see the theme in action here.
keywords: Hexo, Theme, Redefine, Demo, Site, hexo-theme-redefine, hexo-theme, simple, pure
author: EvanNotFound
language: en

url: https://redefine.ohevan.com
permalink: :year/:month/:day/:title/

index_generator:
  path: ''
  per_page: 10
  order_by: -date

theme: redefine
