title: Theme Redefine
subtitle: Redefine Theme Demo Site
description: >-
  This is Hexo Theme Redefine official demo site. You can see the theme in
  action here.
keywords: >-
  Hexo, Theme, Redefine, Demo, Site, hexo-theme-redefine, hexo-theme, simple,
  pure
author: EvanNotFound
language: en
timezone: null
url: https://redefine.ohevan.com
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: null
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: HH:mm:ss
per_page: 10
pagination_dir: page
theme: redefine
deploy:
  type: null
theme_config:
  articles:
    code_block:
      highlight_theme:
        light: atom-one-light
        dark: nord
  comment:
    enable: true
    system: twikoo
  footer:
    runtime: false
  plugins:
    aplayer:
      enable: true
      type: fixed
