name: Publish to NPM

on:
  release:
    types: [published]
  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          runtime: node@24
          cache: true

      - name: Publish package
        run: pnpm publish --provenance
